[[main]]
	name = "Articles"
	pageRef = "posts"
	url = "/posts/"
	weight = 1

[[main]]
	name = "A propos"
	pageRef = "a-propos"
	url = "/a-propos/"
	weight = 3

[[main]]
	name = "Write-up"
	pageRef = "write-up"
	url = "/write-up/"
	weitght = "2"
