baseURL = 'https://nathan-out.github.io/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
theme = "congo"
list.showSummary = true
summaryLength = 10
outputs.home = ["HTML", "RSS", "JSON"]
publishDir = "docs"
[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
[site]
